### ISSUE TITLE
请问能否去掉上拉和下拉提示信息呢？

### ISSUE THREAD

**Issue by yuzhongxingke** [noahlu/NLBouncePagination#2]
比如上拉的时候直接可以拉倒subview 的部分界面，松开跳转到 subview 上，同样，下拉直接显示 mainview 的部分界面，松开动画到 mainview 上，这样体验应该比较好，能否实现呢？多谢啦

**Comment by noahlu** [comment]
这个控件的实现方案是用两个scrollview套在一起，因此要提前显示下一页，得使用其他方案啦。
